### ISSUE TITLE
Tyml

### ISSUE THREAD

**Issue by hediet** [henry-luo/mark#1]
Quite some time ago, I started working at a similar project (https://github.com/tyml/specification). However, due to technical issues and not much free time, I had to pause the development.
It's funny that we came up with similar ideas!

**Comment by henry-luo** [comment]
Thanks for suggesting Tyml! It's my first time getting to know it. They indeed share many similar ideas.
Great minds think alike! ;-)

Tyml documentation is incomplete, so a hit hard for me to grasp its full design.

Is there any good design or idea that Mark can borrow from Tyml?

**Comment by hediet** [comment]
Hi, there are quite a few things that make Tyml different from Mark and still worth to pursue. If you want, we can have a skype or telegram chat and exchange ideas.

**Comment by henry-luo** [comment]
we can use skype to chat

**Comment by hediet** [comment]
My skype name is henning.dieterichs@live.de, looking forward to exchange ideas with you!

**Comment by henry-luo** [comment]
Since we are connected already. I'll close this issue.
