### ISSUE TITLE
Make official grammar LR(1)

### ISSUE THREAD

**Issue by TedDriggs** [henry-luo/mark#4]
The current grammar for mark objects has a local ambiguity: A `string` encountered after the `type_name` could be the key of a property or the first item in `contents`. Having one canonical LR(1) grammar would make it easier to implement parsing and deserialization libraries in different languages.

**Comment by henry-luo** [comment]
Thanks for the feedback.

I'd very much like the syntax to be as simple as LR(1), but in this case, it will be too restrictive for the syntax design. To make it LR(1), the property key will have to be only identifiers, like in HTML/XML, and we'll break JSON compatibility, which is something I don't want to forgo. And different languages accept different characters for identifier.

There might be other options, e.g. only use single quote '...' for property key, and double quote "..." for text. Will people like such design?

Mark grammar is currently LL(k). Not that hard to implement a parser manually. I don't know if the adoption widens, whether there will be challenge for other tools and languages.

Unless we have other good option, the syntax design for this case will probably stay as it is.

**Comment by TedDriggs** [comment]
I was under the impression the grammar could be made LR(1) without changing the user-facing grammar by defining additional intermediate tokens. If that's incorrect then I rescind the suggestion.

**Comment by henry-luo** [comment]
Sorry. I might get you wrongly. You are just suggesting to rewrite the BNF grammar, to eliminate the ambiguity, e.g. by factoring out the left-side common factor, is it?
If that what you mean, it can be considered. 

I'm not expert into the grammar details. Any explicit suggestion of change to the grammar, or pull request is welcome.

**Comment by robotacon** [comment]
Would it be too intrusive to require a text property like so?
{label for:"pwd" text:"Password"}

**Comment by henry-luo** [comment]
May I know what you mean by 'a text property'?

Mark currently does not reserve any property name, so the word 'text' can be used as a property name. The example you gave above is fine in Mark.

**Comment by robotacon** [comment]
That's what I meant ie adding a reserved word for text. But it's understandable that reserving a property name would not be good for Mark.

And a text-property could still be used (like you pointed out) for a specific application where LR is favorable.

The reason I asked in the first place is that I often use a text-property when working with JSON (for instance when initializing a html element) with no negative impact. My interest in Mark is basically to see if I can use it as a better alternative to JSX which I dislike to no end.

**Comment by henry-luo** [comment]
I just tested, old browsers have this restriction that property name cannot be a reserved keyword like 'class', so {class:'...'} would be invalid in old browsers like IE8, but you can quote it, and {'class':'...'} is valid. It's only a restriction on syntax, not on the data model.

But the word 'text' is not a reserved word in JS. I just tested in IE7 and IE8, {text:'...'} is accepted in both of them. I saw some [site](http://www.javascripter.net/faq/reserved.htm) advises not to use 'text' as property name, but that's just an advice of good practice, not a restriction.

As for alternative to JSX, you can try out Mark Template, the implementation is already in good shape, just missing full documentation at the moment.

**Comment by TedDriggs** [comment]
@henry-luo I don't have the bandwidth at the moment to figure out exactly how to structure this; I may end up implementing it as something that produces an array of `PropertyOrContent` and then returns an error after initial parsing if they don't adhere to the required order.

**Comment by henry-luo** [comment]
@TedDriggs As this [paper ](http://www.antlr2.org/article/needlook.html)(by producer of ANTLR) suggests, while LR(1) is simpler to implement, a grammar in LR(1) might not always readable. LR(k) grammar might sometimes needed to make the grammar more readable.

In [theory](https://stackoverflow.com/questions/20683692/lrk-to-lr1-grammar-conversion), LR(k) can be transformed into LR(1). And parsers are getting more powerful to handle LL(k) or LR(k) grammar.

Since we both don't have bandwidth to look into the details, I suggest we close this issue for the time being.
