### ISSUE TITLE
optional closing hint

### ISSUE THREAD

**Issue by pannous** [henry-luo/mark#5]
please allow for optional closing hints at the end of braces:
```
{html
# some 100 lines later
}html
```

or

```
html{
# some 100 lines later
html}
```

The inventors of xml had good reasons to have named closing tags for long documents.
`(lisp( like (brace ((((    forests existed  ))) before ))))`

**Comment by henry-luo** [comment]
You can do it as following:
`{html
# some 100 lines later
} //html`
Such practice is common in C, Java, JS, etc. with deep nested blocks of code.

I don't think there's need to introduce new syntax.

**Comment by pannous** [comment]
fair enough
